# config.yaml

api_tmdb:
  base_url: "https://api.themoviedb.org/3"
  timeout: 5
  language: "en-EN"

paths:
  ratings: "../data/raw/movie_lens/ratings.csv"
  links: "../data/raw/movie_lens/links.csv"

database:
  host: "localhost"
  port: 5432
  name: "mon_projet"
